### ISSUE TITLE
how are you  propesor, it is me sintayehu 

### ISSUE THREAD

**Issue by 091356** [snkim0701/Optimal-and-Adaptive-Control#1]

**Comment by 091356** [comment]
how are you  pro.snkim,it is me sintayehu

**Comment by snkim0701** [comment]
p{margin-top:0;margin-bottom:0}
    


    

                                                                                                             Seungnam Kim 
Ph.D/ Professor
School of Electrical and Computing Engineering , ASTU                                                                +251 99 480  7269   snkim0701@daum.net                                                                                                                                                         

--------- 원본 메일 ---------

    
        보낸사람: 091356 <notifications@github.com>
        받는사람: snkim0701/Optimal-and-Adaptive-Control <Optimal-and-Adaptive-Control@noreply.github.com>
        
            참조: Subscribed <subscribed@noreply.github.com>
        
        날짜: 20.03.18 05:48 GMT +0900
        제목: Re: [snkim0701/Optimal-and-Adaptive-Control] how are you  propesor, it is me sintayehu  (#1)
        
        
    
    
        
how are you  pro.snkim,it is me sintayehu
